services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: ${POSTGRES_USER:-appsenhas}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-appsenhas}
      POSTGRES_DB: ${POSTGRES_DB:-appsenhas}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-appsenhas} -d ${POSTGRES_DB:-appsenhas}"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: ./api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      TZ: America/Sao_Paulo
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-appsenhas}:${POSTGRES_PASSWORD:-appsenhas}@db:5432/${POSTGRES_DB:-appsenhas}
      APP_SECRET_KEY: ${APP_SECRET_KEY:-}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@compuflow.local}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin123}
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:3000,http://127.0.0.1:3000,http://web:3000}
      ADMIN_WEB_URL: ${ADMIN_WEB_URL:-http://localhost:3000}
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY:-}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY:-}
      VAPID_EMAIL: ${VAPID_EMAIL:-}
    ports:
      - "5000:5000"
    volumes:
      - uploads_data:/app/static/uploads
      - api_instance:/app/instance

  web:
    build:
      context: ./web
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:5000}
        API_INTERNAL_URL: ${API_INTERNAL_URL:-http://api:5000}
    restart: unless-stopped
    depends_on:
      - api
    environment:
      API_INTERNAL_URL: ${API_INTERNAL_URL:-http://api:5000}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:5000}
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  uploads_data:
  api_instance:
